// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservasCanchaSintetica;

#nullable disable

namespace ReservasCanchaSintetica.Migrations
{
    [DbContext(typeof(CanchaSinteticaContext))]
    partial class CanchaSinteticaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.35");

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.Administrador", b =>
                {
                    b.Property<string>("Documento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Documento");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.Cancha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.CanchaXReservaTorneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanchaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdCancha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdReservaTorneo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservaTorneoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.HasIndex("ReservaTorneoId");

                    b.ToTable("CanchaXReservaTorneos");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.Cliente", b =>
                {
                    b.Property<string>("Documento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Saldo")
                        .HasColumnType("REAL");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Documento");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.DiaBloqueado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DiasBloqueados");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadJugadores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadAguas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadBalones")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanchaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadAguas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadBalones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadHoras")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteDocumento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentoCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdCancha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("PrecioTotal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.HasIndex("ClienteDocumento");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.ReservaTorneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdministradorDocumento")
                        .HasColumnType("TEXT");

                    b.Property<int>("CanchaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadAguas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadBalones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadHoras")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentoAdministrador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdCancha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdTorneo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TorneoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorDocumento");

                    b.HasIndex("CanchaId");

                    b.HasIndex("TorneoId");

                    b.ToTable("ReservaTorneos");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.Torneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Premio")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorInscripcion")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.TorneoXEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTorneo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TorneoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("TorneoId");

                    b.ToTable("TorneoXEquipos");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.CanchaXReservaTorneo", b =>
                {
                    b.HasOne("ReservasCanchaSintetica.Modelos.Cancha", "Cancha")
                        .WithMany("CanchaXReservaTorneos")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservasCanchaSintetica.Modelos.ReservaTorneo", "ReservaTorneo")
                        .WithMany("CanchaXReservaTorneos")
                        .HasForeignKey("ReservaTorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("ReservaTorneo");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.Reserva", b =>
                {
                    b.HasOne("ReservasCanchaSintetica.Modelos.Cancha", "Cancha")
                        .WithMany("Reservas")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservasCanchaSintetica.Modelos.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteDocumento");

                    b.Navigation("Cancha");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.ReservaTorneo", b =>
                {
                    b.HasOne("ReservasCanchaSintetica.Modelos.Administrador", "Administrador")
                        .WithMany()
                        .HasForeignKey("AdministradorDocumento");

                    b.HasOne("ReservasCanchaSintetica.Modelos.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservasCanchaSintetica.Modelos.Torneo", "Torneo")
                        .WithMany("ReservaTorneos")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrador");

                    b.Navigation("Cancha");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.TorneoXEquipo", b =>
                {
                    b.HasOne("ReservasCanchaSintetica.Modelos.Equipo", "Equipo")
                        .WithMany("TorneoXEquipos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservasCanchaSintetica.Modelos.Torneo", "Torneo")
                        .WithMany("TorneoXEquipos")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.Cancha", b =>
                {
                    b.Navigation("CanchaXReservaTorneos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.Equipo", b =>
                {
                    b.Navigation("TorneoXEquipos");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.ReservaTorneo", b =>
                {
                    b.Navigation("CanchaXReservaTorneos");
                });

            modelBuilder.Entity("ReservasCanchaSintetica.Modelos.Torneo", b =>
                {
                    b.Navigation("ReservaTorneos");

                    b.Navigation("TorneoXEquipos");
                });
#pragma warning restore 612, 618
        }
    }
}
